### ISSUE TITLE
How to get access to original payloads posted by clients?

### ISSUE THREAD

**Issue by shaunlandau1973** [rvolosatovs/docker-protobuf#109]
Sometimes clients post payloads with incorrect field names. These field values are lost since they do not have designated fields in target structs. Is it possible to have the generated grpc code expose the raw, unadulterated payload bytes in the context object passed to the handlers?

**Comment by rvolosatovs** [comment]
I'm not sure this belongs in this repository. Did you mean to ask in https://github.com/grpc/grpc or https://github.com/protocolbuffers/protobuf ?
Closing, because not clear what is expected here
