### ISSUE TITLE
[Feature]: Add nanopb support

### ISSUE THREAD

**Issue by chenjingyuanku** [rvolosatovs/docker-protobuf#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dynamic memory allocation is mandatory in **protobuf-c**, but it is a resource-consuming practice to use dynamic memory allocation in many embedded devices. Even some low-end chips do not support malloc operation, while **nanopb** can use static memory allocation to perform encoding and decoding operations, so we hope to add **nanopb** support.

### Suggestions for a technical implementation

https://github.com/nanopb/nanopb

**Comment by strophy** [comment]
@chenjingyuanku thanks for your feature request, I have attempted an initial naive implementation in #180 

Are you familiar with building nanopb? I have a couple of questions:
- The binary build still depends on 33MB of Python libraries, which would greatly increase the size of the final image. Is there any way to build a binary that doesn't depend on the presence of a Python runtime?
- Is there any way to build this for `aarch64`? `tools/make_linux_package.sh` seems to assume the platform is `linux-x86` but this is not always the case here. Can we do a PR to support different arch in this build script?

**Comment by chenjingyuanku** [comment]
It uses `Pyinstaller` to package python source code into binary, I think `aarch64` and `x86` use the same package command. But since it uses `Pyinstaller`, it is unavoidable that the packaged binary contains the python runtime. I don't know if my understanding is correct.
