### ISSUE TITLE
4.1.0 release not available on docker-hub

### ISSUE THREAD

**Issue by nsteinmetz** [rvolosatovs/docker-protobuf#224]
Hi there,

First, thanks for the job you do with this image, it's very appreciated.

Seems the github actions run did not complete successfully and thus, the 4.1.0 image is not available on github.

Cf https://github.com/rvolosatovs/docker-protobuf/actions/runs/5377667314

Could you please review and fix this ?

Thanks !

**Comment by strophy** [comment]
@nsteinmetz thanks for the heads up! Did you mean GitHub or Docker Hub? It looks like a transient error we encounter sometimes in CI if the Dart build can't pull a package on first try. Re-running the build seemed to fix it and 4.1.0 has now been pushed to Docker Hub.

This version might have an issue with JS on the arm64 image, feel free to open another issue if something doesn't work.

**Comment by nsteinmetz** [comment]
I meant dockerhub and 4.1.0 tag appears two days ago indeed.

Thanks !
