### ISSUE TITLE
Release v4.2.0

### ISSUE THREAD

**Issue by strophy** [rvolosatovs/docker-protobuf#355]
@rvolosatovs how do we do release? Can you release v4.2.0? All current issues were resolved, I'll try and add [pbandk](https://github.com/streem/pbandk) next.

Out of curiosity, how many people currently use this tool, can you see download stats on Docker Hub?

**Comment by rvolosatovs** [comment]
> @rvolosatovs how do we do release? Can you release v4.2.0? All current issues were resolved, I'll try and add [pbandk](https://github.com/streem/pbandk) next.
> 
> Out of curiosity, how many people currently use this tool, can you see download stats on Docker Hub?

I can see that the images are actively pulled, but can't find the exact stats.
Regarding the release, I think we need to go straight to 5.0.0, since `java` support is removed, which is not a backwards-compatible change.

I'll do a release shortly

**Comment by rvolosatovs** [comment]
done! https://github.com/rvolosatovs/docker-protobuf/releases/tag/v5.0.0
