### ISSUE TITLE
Include protoc-gen-swagger/protoc-gen-openapi plugin

### ISSUE THREAD

**Issue by leonteq-reisg** [rvolosatovs/docker-protobuf#359]
The plugin `protoc-gen-swagger` was included in the original project `znly/docker-protobuf`, but seems to have been removed here. Is there a reason for that, and can we include the plugin again?
Thanks!

**Comment by strophy** [comment]
I think `protoc-gen-swagger` evolved into `protoc-gen-openapiv2` from https://github.com/grpc-ecosystem/grpc-gateway which is already included in the image. While trying to figure this out I realized we don't actually test these generators when building the image, can you see if using the generators as shown in the examples in #360 works for you?

**Comment by leonteq-reisg** [comment]
It works, but only after adding `option go_package = ...` to all the proto files. This would require some changes in all our proto files, but is definitely an option to consider. 
Thanks!
