### ISSUE TITLE
Automate package updates

### ISSUE THREAD

**Issue by rvolosatovs** [rvolosatovs/docker-protobuf#44]
#### Summary

It would be great if package updates could be automated

#### Why do we need this?

To reduce maintenance resources required

#### What is already there? What do you see now?

Manual update PRs like #42 
`check-versions.go` is used for newest version fetching and then the output is manually compared to the contents of `build.sh`

#### What is missing? What do you want to see?

Check versions and open automated PRs if packages are out-of-date.

#### Environment

CI

#### How do you propose to implement this?

Run a cron job, which would check that latest versions available and open a PR if there are out-of-date packages. Maybe this could be done with Github Actions.

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by strophy** [comment]
I believe this can be achieved with GitHub Actions and the Renovate bot regex module, which works similar to Dependabot

https://docs.renovatebot.com/modules/manager/regex/

**Comment by rvolosatovs** [comment]
> I believe this can be achieved with GitHub Actions and the Renovate bot regex module, which works similar to Dependabot
> 
> [docs.renovatebot.com/modules/manager/regex](https://docs.renovatebot.com/modules/manager/regex/)

Never heard of it, but if it works, then that would be fantastic

**Comment by strophy** [comment]
Closed in #122
