### ISSUE TITLE
`protoc-gen-swift` and `protoc-gen-grpc-swift` doesn't run on Alpine image based container

### ISSUE THREAD

**Issue by e-sung** [rvolosatovs/docker-protobuf#77]
#### Summary

`protoc-gen-swift` and `protoc-gen-grpc-swift` doesn't run on Alpine Image based container.
It only runs properly on Ubuntu Image based container

#### Steps to Reproduce

1. `docker run --rm -it --name protoc --entrypoint /bin/sh thethingsindustries/protoc:development`
2. `protoc-gen-swift --version`

#### What do you see now?

```shell
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libswiftCore.so)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicuucswift.so.65)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicuucswift.so.65)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicuucswift.so.65)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicui18nswift.so.65)
./protoc-gen-grpc-swift: /usr/lib/libstdc++.so.6: no version information available (required by /protoc-gen-swift/libicui18nswift.so.65)
./protoc-gen-grpc-swift: Relink `/usr/lib/libstdc++.so.6' with `/protoc-gen-swift/libm.so.6' for IFUNC symbol `floor'
Segmentation fault (core dumped)
```

#### What do you want to see instead?

`protoc-gen-swift 1.9.0`

#### Environment

```
The Things Network Command-line Interface: ttn-lw-cli
Version:             3.12.2
Build date:          2021-04-30T08:48:12Z
Git commit:          3403b3955
Go version:          go1.16.3
OS/Arch:             darwin/amd64
```

#### How do you propose to implement this?

The `protoc-gen-swift` and `protoc-gen-grpc-swift`  works fine on "Ubuntu Image based Container".
It only doesn't work when it is run on alpine image based container. I'm currently not sure what's the fundemental difference between the two containers, but I think that finding that difference should be the key to resolve the issue. 

This behavior was introduced by https://github.com/TheThingsIndustries/docker-protobuf/pull/76 . If you revert the PR, `protoc-gen-swift` and `protoc-gen-grpc-swift` would at least work.

**Comment by e-sung** [comment]
I assume https://github.com/TheThingsIndustries/docker-protobuf/blob/12da98bd97879d76f2b0f733627e7c5fc2ac7f17/Dockerfile#L195 were supposed to make `protoc-gen-swift` plugins to run on Alpine based container. I guess something should be done here.

**Comment by rvolosatovs** [comment]
Previous issue regarding this: https://github.com/TheThingsIndustries/docker-protobuf/issues/57

**Comment by rvolosatovs** [comment]
I have added a test:
https://github.com/rvolosatovs/docker-protobuf/blob/f38a9f592dde77dad36382b6be62d982b22337e3/Dockerfile#L409-L410

Both plugins execute successfully on amd64.
Closing this for now, please reopen if you still experience issues (you can test `4.0.0-rc2` release)
