### ISSUE TITLE
`grpc-java` support on `arm64`

### ISSUE THREAD

**Issue by rvolosatovs** [rvolosatovs/docker-protobuf#93]
`grpc-java` `arm64` package is missing in Alpine package repositories https://pkgs.alpinelinux.org/packages?name=grpc-java&branch=edge

**Comment by strophy** [comment]
@wenerme I believe you are the maintainer of `grpc-java` on Alpine Linux, sorry for pinging you out of nowhere! I wonder if you could add `arm64` support to the package you maintain here: https://pkgs.alpinelinux.org/packages?name=grpc-java

Or point me to where the code is so I can attempt it myself? Thank you!

**Comment by wenerme** [comment]
@strophy ok, let me try

**Comment by wenerme** [comment]
Done 
edge https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/39607
3.16 https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/39608

**Comment by strophy** [comment]
Thanks @wenerme so much for the fastest response ever!

**Comment by strophy** [comment]
@rvolosatovs https://github.com/rvolosatovs/docker-protobuf/pull/107
